#Configuration file for RestartMe v1.1.0
broadcastInterval: 1200
#Sets the interval of the countdown before broadcast, in seconds
broadcastMessage: "§eServer will restart in {RESTART_FORMAT_TIME}."
#Sets the message format, will broadcast at the intervals set in broadcastInterval, refer to values.txt for entire list of usable values
countdownMessage: "Server restarting in {RESTART_TIME}..."
#Sets the message format, will broadcast during countdown, refer to values.txt for entire list of usable values
displayType: chat
#Sets how players get the countdown message, two options: chat, popup
memoryLimit: 1200M
#Sets the max memory that can be allocated before server restarts due to overload
#B = byte; K = kilobyte; M = megabyte; G = gigabyte; T = terabyte; P = petabyte
overloadQuitMessage: "§eServer restarted due to overload."
#Sets the message sent to a player when they are kicked because of a server restart triggered by a memory overload
quitMessage: "§aServer restarted."
#Sets the message sent to a player when they are kicked because of a server restart
restartInterval: 90
#Sets the interval of the server restart, in minutes
restartOnOverload: false
#Set to true to allow server restarts when the server's memory is overloaded
startCountdown: 10
#Sets the time when to initiate a countdown, n seconds from restarting